### ISSUE TITLE
If a comma is used as a thousands separator, then a product's price is incorrectly saved on the product's save

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/currency-format#2]
[mage2.pro/t/5656](https://mage2.pro/t/5656)

![](https://mage2.pro/uploads/default/original/2X/1/1f7c79abe19ea62c18ec69e790eaeb8a8b5996a5.png)

![](https://mage2.pro/uploads/default/original/2X/8/8cee5f5a8d277d30911ac4b7d33f9ef89525bf25.png)

**Comment by dmitrii-fediuk** [comment]
Fixed in [1.1.0](https://github.com/mage2pro/currency-format/releases/tag/1.1.0).

**Comment by woshka** [comment]
hello,
I used your module https://github.com/mage2pro/currency-format
although it has been reported earlier about this issue and also mentioned in the files of this module as fixed
* 2018-08-30
	 * «If a comma is used as a thousands separator,
	 * then a product's price is incorrectly saved on the product's save»:
	 * https://github.com/mage2pro/currency-format/issues/2
but I still have this issue with the latest version of magento 2.1.15 Persian Language
when thousand format delimiter for prices is chosen th price will be saved wrong

but without any thousand delimiter which is by choosing none there is no issues
![2018-10-21_3-55-12](https://user-images.githubusercontent.com/9154074/47261855-a4a9f080-d4e5-11e8-9749-9db802280c25.png)
![2018-10-21_3-55-57](https://user-images.githubusercontent.com/9154074/47261856-a4a9f080-d4e5-11e8-85df-03ee232d524f.png)

**Comment by dmitrii-fediuk** [comment]
Please provide your website's URL.
